### ISSUE TITLE
Inversion problem

### ISSUE THREAD

**Issue by cleversomeday** [Anemy/svgurt#27]
Hi and thanks again for a fun and useful tool. I am seeing the resultant image invert in many instances, when invert is not selected and can't seem to find settings to correct.
<img width="1259" alt="Screen Shot 2019-10-24 at 3 39 44 PM" src="https://user-images.githubusercontent.com/20669470/67520539-0c55c700-f677-11e9-9903-8044f34c0a87.png">

**Comment by Anemy** [comment]
I think this is more how the `minColorRecognized` and `maxColorRecognized` fields in the SVG controls are being used. Currently they're registering average colors that are white (255 rgb). setting the `minColorRecognized` to 0 and `maxColorRecognized` to something like 50 should do the expected behavior.  I'd like to find a way to make these controls a bit more intuitive. Thanks for using the tool!
